// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback:                       1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    edu_chain_nft
    (
        init => init
        upgrade => upgrade
        issueToken => issue_token
        setLocalRoles => set_local_roles
        addIssuer => add_issuer
        removeIssuer => remove_issuer
        isIssuer => is_issuer
        issueCertificate => issue_certificate
        issueCertificateBatch => issue_certificate_batch
        revokeCertificate => revoke_certificate
        verifyCertificate => verify_certificate
        getCertificateAttributes => get_certificate_attributes
        getCertificateNonce => get_certificate_nonce
        getRevocationReason => get_revocation_reason
    )
}

multiversx_sc_wasm_adapter::async_callback! { edu_chain_nft }
