// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ect_anchor
    (
        init => init
        upgrade => upgrade
        anchor => anchor_content
        revokeAnchor => revoke_anchor
        verifyAnchor => verify_anchor
        listAnchorsByAuthor => list_anchors_by_author
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
