// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ect_escrow
    (
        init => init
        upgrade => upgrade
        setEctTokenId => set_ect_token_id
        createSession => create_session
        confirmCompletion => confirm_completion
        disputeSession => dispute_session
        resolveDispute => resolve_dispute
        expireSession => expire_session
        getSession => get_session
        getNextSessionId => get_next_session_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
