// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback:                       1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ect_token
    (
        init => init
        upgrade => upgrade
        issueToken => issue_token
        setLocalRoles => set_local_roles
        addDistributor => add_distributor
        removeDistributor => remove_distributor
        isDistributor => is_distributor
        mintRewards => mint_rewards
        addReward => add_reward
        claimRewards => claim_rewards
        payP2P => pay_p2p
        getPendingBalance => get_pending_balance
        getTreasuryBalance => get_treasury_balance_view
        getTotalDistributed => get_total_distributed
        getTokenId => get_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { ect_token }
